<?php
/**
 * class APIWorkflow
 * Manage custom REST API endpoints and workflows.
 */

namespace VIPWorkflow\Modules;

require_once __DIR__ . '/rest/api-workflow-endpoint.php';

use VIPWorkflow\Modules\Shared\PHP\HelperUtilities;
use VIPWorkflow\Modules\APIWorkflow\REST\APIWorkflowEndpoint;

class APIWorkflow {

	const POST_TYPE = 'vw_api_workflow';
	const SETTINGS_SLUG = 'vw-api-workflow';

	public static function init(): void {
		add_action( 'init', [ __CLASS__, 'register_post_type' ] );
		add_action( 'admin_menu', [ __CLASS__, 'add_admin_menu' ], 7 );
		add_action( 'admin_enqueue_scripts', [ __CLASS__, 'action_admin_enqueue_scripts' ] );

		APIWorkflowEndpoint::init();

		// Register the dynamic routes
		add_action( 'rest_api_init', [ __CLASS__, 'register_dynamic_routes' ] );
	}

	public static function register_post_type(): void {
		register_post_type( self::POST_TYPE, [
			'label'               => __( 'API Workflows', 'vip-workflow' ),
			'public'              => false,
			'show_ui'             => false,
			'capability_type'     => 'post',
			'hierarchical'        => false,
			'rewrite'             => false,
			'query_var'           => false,
			'can_export'          => true,
			'show_in_rest'        => false,
		] );
	}

	public static function add_admin_menu(): void {
		$menu_title = __( 'API Workflows', 'vip-workflow' );
		add_submenu_page( CustomStatus::SETTINGS_SLUG, $menu_title, $menu_title, 'manage_options', self::SETTINGS_SLUG, [ __CLASS__, 'render_admin_view' ] );
	}

	public static function render_admin_view(): void {
		include_once __DIR__ . '/views/manage-api-workflow.php';
	}

	public static function action_admin_enqueue_scripts(): void {
		if ( HelperUtilities::is_settings_view_loaded( self::SETTINGS_SLUG ) ) {
			// Asset file will be generated by webpack
			$asset_file_path = VIP_WORKFLOW_ROOT . '/dist/modules/api-workflow/api-workflow.asset.php';
			if ( file_exists( $asset_file_path ) ) {
				$asset_file = include $asset_file_path;
				wp_enqueue_script( 'vip-workflow-api-workflow-js', VIP_WORKFLOW_URL . 'dist/modules/api-workflow/api-workflow.js', $asset_file['dependencies'], $asset_file['version'], true );
				wp_localize_script( 'vip-workflow-api-workflow-js', 'VW_API_WORKFLOW', [
					'rest_url' => rest_url( 'vip-workflow/v1/api-workflow' ),
					'nonce'    => wp_create_nonce( 'wp_rest' ),
				] );
			}
		}
	}

	public static function register_dynamic_routes(): void {
		$workflows = get_posts( [
			'post_type'   => self::POST_TYPE,
			'post_status' => 'publish',
			'numberposts' => -1,
		] );

		foreach ( $workflows as $workflow ) {
			$config = get_post_meta( $workflow->ID, 'workflow_config', true );
			if ( ! empty( $config ) && is_array( $config ) && isset( $config['endpoint'] ) ) {
				$endpoint = $config['endpoint'];
				register_rest_route( 'vw-api/v1', $endpoint['path'], [
					'methods'             => $endpoint['method'] ?? 'POST',
					'callback'            => function ( $request ) use ( $workflow, $config ) {
						return self::execute_workflow( $workflow, $config, $request );
					},
					'permission_callback' => function () use ( $endpoint ) {
						// Simple auth check for now, can be expanded
						if ( ! empty( $endpoint['api_key'] ) ) {
							$header_key = $_SERVER['HTTP_X_VW_API_KEY'] ?? '';
							return $header_key === $endpoint['api_key'];
						}
						return true;
					},
				] );
			}
		}
	}

	public static function execute_workflow( $workflow, $config, $request ) {
		$data = $request->get_params();
		$context = [
			'request' => $data,
			'headers' => $request->get_headers(),
			'workflow' => $workflow,
		];

		$results = [];
		if ( isset( $config['steps'] ) && is_array( $config['steps'] ) ) {
			foreach ( $config['steps'] as $step ) {
				$results[] = self::execute_step( $step, $context );
			}
		}

		return rest_ensure_response( [
			'success' => true,
			'results' => $results,
		] );
	}

	private static function execute_step( $step, &$context ) {
		switch ( $step['type'] ) {
			case 'php_action':
				if ( ! empty( $step['callback'] ) && is_callable( $step['callback'] ) ) {
					return call_user_func( $step['callback'], $context );
				}
				break;
			case 'webhook':
				return self::send_webhook( $step, $context );
			case 'ingest':
				return self::ingest_data( $step, $context );
		}
		return null;
	}

	private static function send_webhook( $step, $context ) {
		$url = self::parse_template( $step['url'] ?? '', $context );
		$body = self::parse_template( $step['body'] ?? '', $context );

		$response = wp_remote_post( $url, [
			'body'    => $body,
			'headers' => $step['headers'] ?? [],
		] );

		return is_wp_error( $response ) ? $response->get_error_message() : wp_remote_retrieve_body( $response );
	}

	private static function ingest_data( $step, $context ) {
		$post_data = [
			'post_type'   => $step['post_type'] ?? 'post',
			'post_status' => $step['post_status'] ?? 'draft',
			'post_title'  => self::parse_template( $step['post_title'] ?? '', $context ),
			'post_content' => self::parse_template( $step['post_content'] ?? '', $context ),
		];

		$post_id = wp_insert_post( $post_data );

		if ( ! is_wp_error( $post_id ) && ! empty( $step['meta'] ) && is_array( $step['meta'] ) ) {
			foreach ( $step['meta'] as $key => $template ) {
				update_post_meta( $post_id, $key, self::parse_template( $template, $context ) );
			}
		}

		return $post_id;
	}

	private static function parse_template( $template, $context ) {
		if ( ! is_string( $template ) ) {
			return $template;
		}
		return preg_replace_callback( '/{{(.*?)}}/', function ( $matches ) use ( $context ) {
			$path = explode( '.', trim( $matches[1] ) );
			$value = $context;
			foreach ( $path as $segment ) {
				if ( is_array( $value ) && isset( $value[ $segment ] ) ) {
					$value = $value[ $segment ];
				} elseif ( is_object( $value ) && isset( $value->$segment ) ) {
					$value = $value->$segment;
				} else {
					return $matches[0];
				}
			}
			return is_scalar( $value ) ? $value : json_encode( $value );
		}, $template );
	}
}

APIWorkflow::init();
